version: "3"

services:
  bot:
    container_name: "discord_bot.py"
    build: .
    secrets:
      - ssh_key
    volumes:
      - ./data:/discord_bot/data
    restart: always

secrets:
  ssh_key:
    file: $home/.ssh/github_rsa